### ISSUE TITLE
Question about your metric computation

### ISSUE THREAD

**Issue by theodoruszq** [XiaohangZhan/deocclusion#10]
Hi Xiaohang Zhan,

Your framework seems to be elegant and easy to use. And the work you proposed is inspiring. However, I think there is one unreasonable computation on your metric (IOU).
  
https://github.com/XiaohangZhan/deocclusion/blob/c8439ea5c119ec1d2cfab5f8ba4694de88e5b0b4/tools/test.py#L195

As we can see, you sum all foreground pixels and all background pixels together of the whole dataset, and then use the total pixel number to get the final IOU result. As far as my experience, it is not the common style to calculate IOU. Although you also use the computation way for other methods, it is fair in your paper.

Could you please clarify the computation style? I think it significantly enlarges the metric difference between Method `Raw` and Method `PCNet-M`.

Regards,
Qiang Zhou

**Comment by XiaohangZhan** [comment]
I followed the style of mIoU in semantic segmentation that accumulates intersections and unions across the dataset first and then makes the division. Refer to `https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/eval.py`
