### ISSUE TITLE
How to run on my own dataset?

### ISSUE THREAD

**Issue by zzw1123** [XiaohangZhan/deocclusion#11]
Hi, thanks for your contribution!
I want to test the occlusion order on my own dataset, and I notice it need annotation files in demo_kins.ipynb, which I do not have......

**Comment by XiaohangZhan** [comment]
It requires modal masks (instance segmentation masks) as inputs. If your own dataset does not have such annotation, it is not supported.

**Comment by zzw1123** [comment]
modal, bbox, category = read_COCOA(reg, h, w)
Is "modal" the required instance mask in demo_cocoa.ipynb?

**Comment by XiaohangZhan** [comment]
Yes

**Comment by zzw1123** [comment]
Thanks!
