### ISSUE TITLE
box offset of eraser in PCNet-M

### ISSUE THREAD

**Issue by zzw1123** [XiaohangZhan/deocclusion#12]
Hi, I think the offset 
 here https://github.com/XiaohangZhan/deocclusion/blob/c8439ea5c119ec1d2cfab5f8ba4694de88e5b0b4/utils/data_utils.py#L90 should be bbox = (int(offx * w), int(offy * h), w, h).
Is it a bug?

**Comment by XiaohangZhan** [comment]
Actually h always equals to w here, since the input `inst` is always square, see `https://github.com/XiaohangZhan/deocclusion/blob/c8439ea5c119ec1d2cfab5f8ba4694de88e5b0b4/datasets/partial_comp_dataset.py#L86`. However, it's better to fix it to avoid misleading. I will fix it soon, thank you!

**Comment by zzw1123** [comment]
Got it. Thank you!
