### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by JamesLee789** [XiaohangZhan/deocclusion#15]
subprocess.CalledProcessError: Command '['/home/james/anaconda3/bin/python', '-u', 'main.py', '--local_rank=1', '--config', 'experiments/COCOA/pcnet_m/config.yaml', '--launcher', 'pytorch']' returned non-zero exit status 1.

I got this error when I set "python -m torch.distributed.launch --nproc_per_node=2 main.py" in the train.sh file. When I set "python -m torch.distributed.launch --nproc_per_node=1 main.py" ,it failed as well. I tried training your model in a machine with 2 GPUs and Pytorch 1.5.1 installed. How could this be solved? By the way, what's the recommended GPU requirement for training this model? Thank you!

**Comment by XiaohangZhan** [comment]
I recommend using 8 GPUs. Besides, you may try to downgrade your PyTorch. The PyTorch versions I used include 0.4.1 and 1.1

**Comment by JamesLee789** [comment]
Many thanks for your reply. What specific GPU did you use to train your network modules? How much GPU memory and RAM do I need for training them?

**Comment by XiaohangZhan** [comment]
GTX1080TI. I don't think the issue is due to the memory. You may try to switch the pytorch version first.
