### ISSUE TITLE
another segmentation model fails

### ISSUE THREAD

**Issue by wdrink** [XiaohangZhan/deocclusion#17]
hi, I have ran your demo and the results are good, however, when I tried to use the maskrcnn model of pytorch to obtain the bounding boxes and modal information, the inpainting result is bad,  I have visualized the bounding boxes and masks detected by maskrcnn and compared with yours,  and they don't have large difference, so I wonder whether you have encountered this problem? thanks a lot.

**Comment by XiaohangZhan** [comment]
Refer to this issue: https://github.com/XiaohangZhan/deocclusion/issues/14

**Comment by wdrink** [comment]
OK, thanks a lot.

**Comment by wangjk666** [comment]
![amodal_with_content](https://user-images.githubusercontent.com/48371342/88061922-ba58b800-cb9a-11ea-9f1b-37d7b4a1d3fa.jpg)
