### ISSUE TITLE
ValueError: Unterminated string

### ISSUE THREAD

**Issue by G-Meteor** [XiaohangZhan/deocclusion#20]
Hi, when I run `demos/demo_kins.ipynb`, the following error occurs. How should it be solved? Thank you!
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-c9f15809691d> in <module>
      6 annot_path = "../data/KINS/instances_{}.json".format(phase)
      7 
----> 8 data_reader = KINSLVISDataset('KINS', annot_path)

~/fuxian/Self-Supervised_Scene_De-occlusion/deocclusion-master/datasets/reader.py in __init__(self, dataset, annot_fn)
    133     def __init__(self, dataset, annot_fn):
    134         self.dataset = dataset
--> 135         data = cvb.load(annot_fn)
    136         self.images_info = data['images']
    137         self.annot_info = data['annotations']

~/anaconda3/envs/py3-env/lib/python3.7/site-packages/cvbase/io.py in load(file, format, **kwargs)
    114     if format not in processors:
    115         raise TypeError('Unsupported format: ' + format)
--> 116     return processors[format](file, **kwargs)
    117 
    118 

~/anaconda3/envs/py3-env/lib/python3.7/site-packages/cvbase/io.py in json_load(file)
     18     if isinstance(file, str):
     19         with open(file, 'r') as f:
---> 20             obj = json.load(f)
     21     elif hasattr(file, 'read'):
     22         obj = json.load(file)

~/anaconda3/envs/py3-env/lib/python3.7/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,
--> 296         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    297 
    298 

~/anaconda3/envs/py3-env/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

~/anaconda3/envs/py3-env/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~/anaconda3/envs/py3-env/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    351         """
    352         try:
--> 353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
    355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Unterminated string starting at: line 1 column 18350068 (char 18350067)
08/13/2020 08:26:47 PM INFO: Shutdown kernel
08/13/2020 08:26:47 PM WARNING: Exiting with nonzero exit status

**Comment by XiaohangZhan** [comment]
I notice that you use python 2.7, please follow the requirements [here](https://github.com/XiaohangZhan/deocclusion#requirements) to set up the environment.

**Comment by G-Meteor** [comment]
> I notice that you use python 2.7, please follow the requirements [here](https://github.com/XiaohangZhan/deocclusion#requirements) to set up the environment.

I'm really sorry. I found that I made a mistake in the previous question, and the real question has been updated.

**Comment by XiaohangZhan** [comment]
Check if the json file is incomplete when downloading
