### ISSUE TITLE
manipulation

### ISSUE THREAD

**Issue by r0609260** [XiaohangZhan/deocclusion#24]
Hi Xiaohang, I ran your demos and the results are amazing. However, I do not find codes related to image manipulation such as delete, shift, reposition, and swap as you mentioned in your paper. Is it possible to also provide this part? Thanks a lot!

**Comment by XiaohangZhan** [comment]
See https://github.com/XiaohangZhan/deocclusion-demo

**Comment by r0609260** [comment]
Thank you for your reply!
