### ISSUE TITLE
Are the bboxes of COCOA dataset incorrectly used in this code?

### ISSUE THREAD

**Issue by Jiaoma** [XiaohangZhan/deocclusion#25]
Thanks for your code sharing. I'm a fresh man to this problem. When I looked into your ipython demo on COCOA dataset, I found that the amodal completion result of PCNet-M is always inside the bounding box provided by the COCOA dataset. However, the bounding box provided by the COCOA dataset seems only cover the modal annotations. Is it right? If it is true, I will feel confused about using modal bounding box to restrict the amodal completion area of PCNet-M. And I don't know whether it will bring any bad influence to your training stage.
The figures below show an example I captured from demo_cocoa.ipynb. The image id is 2 (in code).
The bounding boxes are:
![image](https://user-images.githubusercontent.com/15938427/93340571-8e3a7a00-f85f-11ea-83a8-f61d3d96e443.png)
The amodal completions are:
![image](https://user-images.githubusercontent.com/15938427/93340640-a4e0d100-f85f-11ea-82ad-35e720ccb38a.png)

**Comment by XiaohangZhan** [comment]
It is not as you described. For example, the left boundry of the completion of the dog in the image is out of the bbox. We enlarged the modal bbox to in the demo.

**Comment by Jiaoma** [comment]
Thank you for your reply. I reread the code and found that the code `size = max([np.sqrt(bbox[2] * bbox[3] * self.config['enlarge_box']), bbox[2] * 1.1, bbox[3] * 1.1])` and function expand_bbox() are used for enlarging the origin bounding boxes. So the boxes used for amodal completion are larger than the original ones. I'm sorry for making the misleading descriptions.  

I checked many amodal completion results of test images in COCOA dataset, most of them are perfectly matched the amodal gts, except some cases, like the one above.
