### ISSUE TITLE
I want to ask：How can I make my own data set?---thanks

### ISSUE THREAD

**Issue by zhenghan408** [XiaohangZhan/deocclusion#30]
How can I make my own COCOA data set?

i see the :http://openaccess.thecvf.com/content_cvpr_2017/papers/Zhu_Semantic_Amodal_Segmentation_CVPR_2017_paper.pdf.
but the tools do not open-source.

**Comment by XiaohangZhan** [comment]
Try https://github.com/wkentaro/labelme

**Comment by zhenghan408** [comment]
想请问一下，在labelme中标注的时候，应该对哪些部分进行标注呢，分为几类呢，比如说：标注需要去遮挡的目标和目标中被遮挡的部分。
万分感谢

**Comment by XiaohangZhan** [comment]
Sorry, this repo does not involve how to annotate an amodal dataset. I cannot provide any suggestions since we did not try it.

**Comment by chh6936** [comment]
> How can I make my own COCOA data set?
> 
> i see the :http://openaccess.thecvf.com/content_cvpr_2017/papers/Zhu_Semantic_Amodal_Segmentation_CVPR_2017_paper.pdf.
> but the tools do not open-source.

Hello! I would like to ask you some questions. Have you successfully made your own data set? But the tool is not open source. Have you found the tool? Thank you.

**Comment by FocusGZL** [comment]
> > How can I make my own COCOA data set?
> > i see the :http://openaccess.thecvf.com/content_cvpr_2017/papers/Zhu_Semantic_Amodal_Segmentation_CVPR_2017_paper.pdf.
> > but the tools do not open-source.
> 
> Hello! I would like to ask you some questions. Have you successfully made your own data set? But the tool is not open source. Have you found the tool? Thank you.

I have the same question, Have you found the tool?Thank you.
