### ISSUE TITLE
Order matrix not correct even after adjusting 'th' and 'dilate_kernel'

### ISSUE THREAD

**Issue by jiunyen-ching** [XiaohangZhan/deocclusion#32]
Hi, I was testing out the demo codes on this RGB image 
![image](https://user-images.githubusercontent.com/25114361/109425848-60b84600-7a25-11eb-9c46-e9c3a71c8e43.png)

and its instance mask
![image](https://user-images.githubusercontent.com/25114361/109425861-6dd53500-7a25-11eb-870c-d9d4d8663a96.png)

I slowly increased the 'th' and 'dilate_kernel' from (0.1, 5), (0.3, 7), (0.5, 9), (0.7, 11) respectively as advised in #14 but the order matrix is still not correct.

![image](https://user-images.githubusercontent.com/25114361/109425931-c7d5fa80-7a25-11eb-8bbb-6f5ec2368792.png)

From the order matrix, Instance 3 (table) is not considered as an occluder to Instance 5 (bench). May I ask for some advice as to how to improve the situation?

**Comment by XiaohangZhan** [comment]
Why are there margins between objects in the segmentation map? These may severely affect the results. Dilation process can mitigate it but not thoroughly . You might have to deal with the margins before testing it.

**Comment by jiunyen-ching** [comment]
Unfortunately the margins are due to the NYU annotations. I will dilate the masks and try to infer their order again. Will update here if it works

**Comment by jiunyen-ching** [comment]
The masks not tightly fitting each other is indeed quite troublesome to handle. Only certain cases where the masks are tightly fitting, it works well.
