### ISSUE TITLE
Prediction of amodal mask for own labeled dataset

### ISSUE THREAD

**Issue by zhangyufeng1998** [XiaohangZhan/deocclusion#48]
hi,thanks for youe work!
I labeled the image with the labeling tool as shown
![image](https://user-images.githubusercontent.com/103356215/164015272-67f40ef9-11a8-42d5-b920-68bbdefcabd0.png)
Why does it produce a modal mask and an amodal mask that are almost identical?
Why does it produce 3 boxes？

![image](https://user-images.githubusercontent.com/103356215/164016429-1906a97f-0418-457d-9bd0-346666a0e927.png)

**Comment by kkllww** [comment]
Hello, can you download the released model.

**Comment by jiunyen-ching** [comment]
Hi @zhangyufeng1998, in your annotation screenshot, we can see that you indeed labelled the segments of two leaves correctly. 
![image](https://user-images.githubusercontent.com/25114361/167288944-93767fa7-7f26-466a-97ef-d842ce8e02c9.png)

However, in the visualization step, we can see that there are INPUT 3 modal masks (highlighted by 3 different colors)
![image](https://user-images.githubusercontent.com/25114361/167289039-9be6c2ef-b88d-4fc8-841f-ee4ef92c8ec2.png)

This means that you need to modify the code that reads your annotations to load the masks correctly before you run de-occlusion. Verify that the modal masks are being visualized as how you would expect the masks to be.

**Comment by zhangyufeng1998** [comment]
ok i have got it
now,i open the evaluation issue ,can you help me ? It is the issues 50th

**Comment by wmrenr** [comment]
> Hello, can you download the released model.
Yes, I can download with vpn tool.

**Comment by gardenia0910** [comment]
> hi,thanks for youe work! I labeled the image with the labeling tool as shown ![image](https://user-images.githubusercontent.com/103356215/164015272-67f40ef9-11a8-42d5-b920-68bbdefcabd0.png) Why does it produce a modal mask and an amodal mask that are almost identical? Why does it produce 3 boxes？
> 
> ![image](https://user-images.githubusercontent.com/103356215/164016429-1906a97f-0418-457d-9bd0-346666a0e927.png)

Hello, I am sorry to bother you. I am replicating this code recently, but I want to use my own photos for testing, and I do not know how to generate json files of my own photos. If you know, I hope you can answer me, thank you!

**Comment by fserk729** [comment]
hello @zhangyufeng1998 

how did you make your own dataset for this?
