### ISSUE TITLE
The published model is corrupted

### ISSUE THREAD

**Issue by kkllww** [XiaohangZhan/deocclusion#49]
In the download link you gave, all the published models have been damaged. Can you upload them again.

**Comment by XiaohangZhan** [comment]
You don't have to untar it.

**Comment by kkllww** [comment]
Thank you for your guidance. Now I have preliminarily reproduced it. Next, I'm going to use my own pictures to cover it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaohangZhan/deocclusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaohangZhan/deocclusion] The published model is corrupted (Issue #49)





 
You don't have to untar it.
