### ISSUE TITLE
evaluation issues

### ISSUE THREAD

**Issue by zhangyufeng1998** [XiaohangZhan/deocclusion#50]
Hi, thanks for your work!
If training and validating with a custom dataset, how are the evaluation metrics acc_occpair and miu generated?
Is it the predicted amodal mask and the generated amodal mask annotations ? BecauseThe custom dataset does not contain amodal and order annotations
Can you answer my question? Thanks a lot

**Comment by wmrenr** [comment]
Do you excult his codes on the COCOA or KINS datasets?

**Comment by XiaohangZhan** [comment]
On custom dataset, if you want to evaluate quantitatively, you have to prepare modal and amodal masks, as well as order annotations by yourself. You may also run on given datasets COCOA and KINS.
