### ISSUE TITLE
Question about Loader in demo_cocoa.ipynb

### ISSUE THREAD

**Issue by IvanChen777** [XiaohangZhan/deocclusion#55]
<img width="1076" alt="截屏2022-11-02 11 19 57" src="https://user-images.githubusercontent.com/91310432/199464901-023c5580-29fd-4f7b-9fed-334ff8f5abc7.png">
Hi, I met a problem in demo_cocoa.ipynb, it seems that the problem is from yaml package, then I try to change the yaml.load(f) to yaml.safe_load or full load, or add a argument loader, but the result is still the same. Does someone knows how to deal with this issue? Thank you in advance.

**Comment by Onypony** [comment]
Replace yaml.load(f) with yaml.load(f, Loader=yaml.FullLoader)

**Comment by starryCcchj** [comment]
I have met the same problem. Is there any solution now?

**Comment by liushawn618** [comment]
yaml.safe_load(f) works for me
