### ISSUE TITLE
amodel pred ours

### ISSUE THREAD

**Issue by gardenia0910** [XiaohangZhan/deocclusion#58]
Hello, I found that the amodal_pred_ours image was not marked when I was running, may I ask what the problem might be?
![image](https://github.com/XiaohangZhan/deocclusion/assets/141470900/d42d0246-8643-4677-9b0a-9b5435bdfc94)

**Comment by gardenia0910** [comment]
solved it!

**Comment by wexj** [comment]
I have also encountered the same problem. Could you please tell me how you solved it?
