### ISSUE TITLE
a question about pretrain model

### ISSUE THREAD

**Issue by etoilestar** [XiaohangZhan/deocclusion#6]
when i use the pretrain model from  https://github.com/naoto0804/pytorch-inpainting-with-partial-conv, i get the result: keyerror, can you tell me what's wrong?

**Comment by XiaohangZhan** [comment]
Have you run `python tools/convert_pcnetc_pretrain.py`?

**Comment by etoilestar** [comment]
yes, it returns keyerrror

**Comment by XiaohangZhan** [comment]
Fixed now. Please pull and run it again.

**Comment by etoilestar** [comment]
could you tell me which file I need to replace，if i pull the project it again, it is so difficult.

**Comment by XiaohangZhan** [comment]
tools/convert_pcnetc_pretrain.py
