### ISSUE TITLE
contours = np.subtract(contours, 1) error

### ISSUE THREAD

**Issue by hoya-cho** [XiaohangZhan/deocclusion#60]
ValueError                                Traceback (most recent call last)
Cell In[19], line 42
     40 plt.axis('off')
     41 plt.text(0, -10, title[i])
---> 42 pface, pedge = polygon_drawing(toshow[i], selidx, colors, bbox_show, thickness=3)
     43 ax.add_collection(pface)
     44 ax.add_collection(pedge)

File /deocclusion/demos/demo_utils.py:206, in polygon_drawing(masks, selidx, color_source, bbox, thickness)
    204     masks = masks[:, u:b, l:r]
    205 for i,am in enumerate(masks[selidx,...]):
--> 206     pts_list = reader.mask_to_polygon(am)
    207     for pts in pts_list:
    208         pts = np.array(pts).reshape(-1, 2)

File /deocclusion/datasets/reader.py:286, in mask_to_polygon(mask, tolerance, area_threshold)
    284 contours = measure.find_contours(padded_mask, 0.5)
    285 # Fix coordinates after padding
--> 286 contours = np.subtract(contours, 1)
    287 for contour in contours:
    288     if not np.array_equal(contour[0], contour[-1]):

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

when i infer amodal completion that error occured. how can i solve it?

**Comment by hoya-cho** [comment]
When trying to practice demo_kins.ipynb, can I know the information about the environment you used? I would like to know the version of a library such as numpy.

**Comment by hoya-cho** [comment]
i solved it

**Comment by Borui66111** [comment]
hi, can you please share how you resolved this issue?
