### ISSUE TITLE
The masks we should prepare should be amodal or modal?

### ISSUE THREAD

**Issue by b-niu** [XiaohangZhan/deocclusion#61]
Dear author, thanks for such a wonderful work which may make great help to instance segmentation tasks.

I noticed that in the Readme, 

>**Using your own dataset**
>If using your own dataset to train or test, you need to make sure that it contains accurate **modal annotations** (masks are required >and categories are optional). Inaccurate **modal mask** annotations, e.g., COCO original annotaions that may have large margin >between masks of occluding objects, will result in unsatisfactory results.

However, the masks in "**COCOA dataset proposed in [Semantic Amodal Segmentation]**" are amodal.

I am confused that, should we prepare modal masks or amodal masks?

Thanks a lot.

**Comment by XiaohangZhan** [comment]
If you use your OWN dataset, you should prepare accurate modal masks.
COCOA contains both modal and amodal masks, and the amodal masks are used in evaluation.

**Comment by b-niu** [comment]
Thank you @XiaohangZhan , modal masks should be much easier to be prepared compared to amodal masks.
