### ISSUE TITLE
cocoa annotation download

### ISSUE THREAD

**Issue by wexj** [XiaohangZhan/deocclusion#63]
I tried to download the dataset, but the permissions were denied

**Comment by woaicv** [comment]
我是企业微信上你刚跟我联系跑单子的，中介抽成太多，所以不方便再降价了。看你，愿意直接加我的话能便宜些 v 18361811160。 平台上别乱说哈，这个邮件不回复我就默认继续走平台了

**Comment by wexj** [comment]
我昨天没看着，还有机会吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaohangZhan/deocclusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月30日(星期三) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaohangZhan/deocclusion] cocoa annotation download (Issue #63)





 
我是企业微信上你刚跟我联系跑单子的，中介抽成太多，所以不方便再降价了。看你，愿意直接加我的话能便宜些 v 18361811160。 平台上别乱说哈，这个邮件不回复我就默认继续走平台了

**Comment by XiaohangZhan** [comment]
不要在这里发布无关内容！
