### ISSUE TITLE
a question about pcnet_c

### ISSUE THREAD

**Issue by etoilestar** [XiaohangZhan/deocclusion#8]
excuse me, there is another question, how to get the generated image from pcnet_c?

**Comment by XiaohangZhan** [comment]
See `demos/demo_cocoa.ipynb`

**Comment by etoilestar** [comment]
ok，solved， but i  cannot find the checkpoint gca-dist-all-data.pth mentioned in your code

**Comment by XiaohangZhan** [comment]
Refer to `demos/demo_cocoa.ipynb` to download the model.
